# Generated by Django 5.2.1 on 2025-09-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bbc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ББК'),
        ),
        migrations.AddField(
            model_name='book',
            name='marc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MARC'),
        ),
        migrations.AddField(
            model_name='book',
            name='udc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='УДК'),
        ),
    ]
