# Generated by Django 5.2.2 on 2025-08-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='books/', verbose_name='Файл книги'),
        ),
        migrations.AddField(
            model_name='book',
            name='file_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на книгу'),
        ),
    ]
